version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    # cap_drop:
    #   - all
    # cap_add:
    #   - NET_BIND_SERVICE
    ports:
      - "8080:80" # local:container
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bigmemes123
      MYSQL_DATABASE: loginjection
    volumes:
      - ./private/create_admin.sql:/docker-entrypoint-initdb.d/create_admin.sql
