# Based on https://github.com/justcatthefish/justctf-2019/blob/master/challenges/web_firmwareupdater/private/Dockerfile
FROM php:7.4-apache

COPY ./private/index.html /var/www/html
COPY ./private/flag.php /var/www/html
COPY ./private/flag.txt /etc/flag
